POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NjVkZDkyOTM1NjYxMWVmMGFhYTNhZWUiLCJpYXQiOjE3MTc0MjY3NDl9.JyY8nH7GB0wX-SHaeJX_Q1gsiVKjQRKmmQ7Kr1n1eZ8

{
    "title": "Microservives and the First Law of Distributed Objects",
    "author": "Martin Fowler",
    "url": "https://martinfowler.com/articles/distributed-objects-microservices.html",
    "likes" : 3
}